name: Create Lockfile

on: workflow_dispatch

jobs:
  create-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install -g pnpm

      - name: Generate lockfile
        run: |
            rm -rf node_modules
            rm -rf pnpm-lock.yaml
            pnpm install --force

      - name: Commit lockfile
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add pnpm-lock.yaml
          git commit -m "Generate pnpm-lock.yaml"
          git push
