name: Create Lockfile

on: workflow_dispatch

jobs:
  create-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: |
          npm i -g pnpm

      - name: Install dependencies required for Sharp
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libvips libvips-dev libxi-dev libxext-dev libxt-dev libgl-dev

      - name: Generate lockfile
        run: |
            rm -rf node_modules
            rm -rf pnpm-lock.yaml
            pnpm install --force

      - name: Commit lockfile
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add pnpm-lock.yaml
          git commit -m "Generate pnpm-lock.yaml"
          git push
